### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'read_gt_csv'

### ISSUE THREAD

**Issue by DDD1213842** [bierschi/nclt2ros#4]
When I ran convert. launch using Ubuntu 20.04, the code displayed the following error:
/usr/lib/python3/dist packages/requests/__ Init__ Py: 89: RequestsDependencyWarning: urllib3 (2.1.0) or charge (5.2.0) does not match a supported version!
Warnings. warn ("urllib3 ({}) or charged ({}) does not match a supported"
Traceback (most recent call last):
File "/home/ddd/NCLT/src/nclt2ros/scripts/nclt2rosbag", line 27, in<module>
Main()
File "/home/ddd/NCLT/src/nclt2ros/scripts/nclt2rosbag", line 22, in main
Converter. process()
File "/home/ddd/NCLT/src/nclt2ros/nclt2ros/converter/to_rosbag. py", line 113, in process
Gt_ List=self.gt.read_ Gt_ Csv (all_in_one=True)
AttributeError: 'bool' object has no attribute 'read_ Gt_ CSV '

**Comment by DDD1213842** [comment]
The whole person is about to collapse，too! Thanks to the one who can help me!!!

**Comment by zhh2005757** [comment]
Did you download gt files by download.launch?
